name: CI
on:
  push:
    branches:
      - "main"
jobs:
  release:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      # - run: npm ci
      - run: yarn install --frozen-lockfile --ignore-platform
      # - run: yarn test
      - run: mkdir lib && yarn build && ls -al ./lib
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ls -al && cd ./lib && npx semantic-release
